SET TRANSACTION ISOLATION LEVEL SNAPSHOT 
BEGIN TRAN
SELECT * FROM Tasks WHERE task_id>2
WAITFOR DELAY '00:00:05'
SELECT * FROM Tasks WHERE task_id>2

UPDATE Tasks SET title='isolationT2' WHERE task_id>2
COMMIT TRAN