-- T2

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Tasks
WAITFOR DELAY '00:00:05'
SELECT * FROM Tasks
COMMIT TRAN


SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Tasks
WAITFOR DELAY '00:00:05'
SELECT * FROM Tasks
COMMIT TRAN