DELETE FROM Tables
SELECT * FROM Tables

DBCC CHECKIDENT ('Tables', RESEED, 0)
GO

DELETE FROM Views
SELECT * FROM Views

DBCC CHECKIDENT ('Views', RESEED, 0)
GO

SELECT * FROM TestRunTables
DELETE FROM TestRunTables

DBCC CHECKIDENT ('TestRunTables', RESEED, 0)
GO

SELECT * FROM TestRunViews
DELETE FROM TestRunViews

DBCC CHECKIDENT ('TestRunViews', RESEED, 0)
GO

SELECT * FROM TestTables
DELETE FROM TestTables

DBCC CHECKIDENT ('TestTables', RESEED, 0)
GO

SELECT * FROM TestViews
DELETE FROM TestViews

DBCC CHECKIDENT ('TestViews', RESEED, 0)
GO

DELETE FROM Tests
SELECT * FROM Tests

DBCC CHECKIDENT ('Tests', RESEED, 0)
GO

SELECT * FROM TestRuns
DELETE FROM TestRuns

DBCC CHECKIDENT ('TestRuns', RESEED, 0)
GO